### ISSUE TITLE
Filesystem Issues

### ISSUE THREAD

**Issue by gmcvey-gear4music** [rev42/tfpdf#11]
In order to use unicode fonts this library seems to require write access to hard-coded filesystem locations.  We're trying to use this library on Google App engine, which provides a read-only filesystem, meaning that we can't use this library for rendering unicode PDFs (which is what we need it for in the first place!)  

Filesystem interactions need to be abstracted out to some sort of plugin architecture (dependency injected classes that implement a specific interface?) so that users of the library can point filesystem operations elsewhere, substitute them with memcache or database backends, etc.  It should also be possible to render documents without actually doing any filesystem writes at all (if you're prepared to accept degraded performance).  In spite of what the readme says, the unifonts directory has to be writable or addfont fails with a number of filesystem warnings.

**Comment by ocornu-mediastay** [comment]
This repository is outdated and will not be updated anymore.

Please create an issue on https://github.com/DocnetUK/tfpdf

**Comment by rev42** [comment]
This repository is outdated and will not be updated anymore.

Please create an issue on https://github.com/DocnetUK/tfpdf
