### ISSUE TITLE
There is no docnet/tFPDF

### ISSUE THREAD

**Issue by slokhorst** [rev42/tfpdf#13]
In the readme, you say to use "docnet/tFPDF" instead, but there is no such Composer package.

https://packagist.org/search/?q=docnet%2FtFPDF

Edit: Also, [DocnetUK/tfpdf](https://github.com/DocnetUK/tfpdf) doesn't allow issues to be opened.. Please don't recommend a repository which the owner doesn't support.

**Comment by mrfu2** [comment]
You really shouldn't abandon https://packagist.org/packages/rev42/tfpdf when https://packagist.org/packages/docnet/tFPDF doesn't exist yet...

**Comment by rev42** [comment]
Hello,

I'm open to discussion.

I never really maintained this package. I added it to packagist because I needed it for some projects.
This class is quite old (2011) and not maintained anymore. Now it exists some great alternatives with great support like https://packagist.org/packages/tecnickcom/tcpdf.

What do you think?

**Comment by slokhorst** [comment]
@rev42, thank you for having it on GitHub/Packagist for all this time!

I would be very happy if we could switch to the @DocnetUK repository, as they seem to actively work on it. However, they don't offer a Composer package, so this is currently impossible. Do you know if they are willing to do that? Maybe I could try to contact them.

The current situation is just not nice. All users of this tFPDF package are redirected to a non-existing one.

**Comment by slokhorst** [comment]
I've popped the question: https://github.com/DocnetUK/tfpdf/pull/8

**Comment by tomwalder** [comment]
DocnetUK here - I'll chat with the team tomorrow and let you know!

**Comment by slokhorst** [comment]
The guys at DocnetUK were so kind to create a Composer package and  open up the GitHub issue tracker. So all is well and @rev42 can finally retire. :)
