### ISSUE TITLE
PHP Fatal error:  Call to undefined function mb_convert_encoding() 

### ISSUE THREAD

**Issue by talent74** [rev42/tfpdf#16]
Like it says above in the title. We are getting the following issue when attempting to download the PDF in Chrome

WP: v4.8.1
Theme: WPGroupBuy
PHP v5.6
 
PHP Fatal error:  Call to undefined function mb_convert_encoding() in ........ tfpdf.php on line 2260

On line 2260:
	$outstr .= mb_convert_encoding($str, 'UTF-16BE', 'UTF-8');

**Comment by rev42** [comment]
Thanks for the report.

This repository is not maintained anymore. Please submit the bug on https://github.com/DocnetUK/tfpdf

Thanks
